version: '2'

services:
  rabbitmq:
    image: 'rabbitmq:3'
    hostname: 'rabbit1'
    labels:
      kompose.service.type: nodeport
    ports:
      - '4369:4369'
      - '5672:5672'
      - '25672:25672'
      - '15672:15672'
    labels:
      NAME: 'rabbitmq1'
    volumes:
      - 'rabbitmq_data:/andreformento'
      - './enabled_plugins:/etc/rabbitmq/enabled_plugins'
  rabbitmq-app:
    image: 'andreformento/rabbitmq-app'
    ports:
      - '8081:8080'
volumes:
  rabbitmq_data:
    driver: local
